language: php

php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - hhvm

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install --dev --no-interaction
  - curl -s https://raw.github.com/yriveiro/travis-solr/master/travis-solr.sh | SOLR_VERSION=4.7.0 bash

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml tests/Sunspot

after_script:
  - php vendor/bin/coveralls -v
